<?php

use Illuminate\Database\Seeder;

class ProductsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        \DB::table('products')->insert(array (
            0 =>
            array (
                'id' => 1,
                'name_en' => 'Apple,Fuji',
                'name_th' => 'แอ๊ปเปิ้ลฟูจิ',
                'price' => 1100,
                'image' => NULL,
                'desc_en' => '18 kg',
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            1 =>
            array (
                'id' => 2,
                'name_en' => 'Apple,Washington Red',
                'name_th' => 'แอ๊ปเปิ้ลแดงวอชิงตัน',
                'price' => 1650,
                'image' => NULL,
                'desc_en' => '18 kg',
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            2 =>
            array (
                'id' => 3,
                'name_en' => 'Apple,Green',
                'name_th' => 'แอ๊ปเปิ้ล เขียว',
                'price' => 1450,
                'image' => NULL,
                'desc_en' => '18 kg',
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            3 =>
            array (
                'id' => 4,
                'name_en' => 'Pisang emas ',
                'name_th' => 'กล้วยไข่',
                'price' => 35,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            4 =>
            array (
                'id' => 5,
                'name_en' => 'Small Banana ,Pisang Awak',
                'name_th' => 'กล้วยน้ำว้า ใหญ่',
                'price' => 27,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            5 =>
            array (
                'id' => 6,
            'name_en' => 'Large Banana (Bunch)',
                'name_th' => 'กล้วยหอม ใหญ่',
                'price' => 38,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            6 =>
            array (
                'id' => 7,
                'name_en' => 'Grapes  Red  seedless',
                'name_th' => 'องุ่นแดงไม่มีเม็ด  ',
                'price' => 1750,
                'image' => NULL,
                'desc_en' => '9 kg',
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            7 =>
            array (
                'id' => 8,
                'name_en' => 'Grapes  Red  ',
                'name_th' => 'องุ่นแดง มีเมล็ด',
                'price' => 850,
                'image' => NULL,
                'desc_en' => '6 kg',
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            8 =>
            array (
                'id' => 9,
                'name_en' => 'Grapes  Green seedless',
                'name_th' => 'องุ่นเขียว ไม่มีเมล็ด',
                'price' => 1850,
                'image' => NULL,
                'desc_en' => '9 kg',
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            9 =>
            array (
                'id' => 10,
                'name_en' => 'Grapes  Black seedless',
                'name_th' => 'องุ่น ดำ  ไม่มีเม็ด',
                'price' => 1850,
                'image' => NULL,
                'desc_en' => '9 kg',
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            10 =>
            array (
                'id' => 11,
                'name_en' => 'Water Melon',
                'name_th' => 'แตงโมแดง  ',
                'price' => 24,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 3,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            11 =>
            array (
                'id' => 12,
                'name_en' => 'Yellow Water Melon',
                'name_th' => 'แคงโมเหลื่อง',
                'price' => 73,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 4,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            12 =>
            array (
                'id' => 13,
                'name_en' => 'Rock Melon',
                'name_th' => 'แตงร็อกกี้เมลลอน',
                'price' => 88,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            13 =>
            array (
                'id' => 14,
                'name_en' => 'Oranges,Sai Nam Pung',
                'name_th' => 'ส้มสายน้ำผึ้ง',
                'price' => 80,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            14 =>
            array (
                'id' => 15,
                'name_en' => 'Oranges Sunkist',
                'name_th' => 'ส้มซันคิสท์',
                'price' => 815,
                'image' => NULL,
                'desc_en' => '1x16kg',
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            15 =>
            array (
                'id' => 16,
                'name_en' => 'Orange, Mandarin',
                'name_th' => 'ส้มแมนดาริน',
                'price' => 915,
                'image' => NULL,
                'desc_en' => '1x10kg',
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            16 =>
            array (
                'id' => 17,
            'name_en' => 'Oranges (SuGun)',
                'name_th' => 'ส้มโชกุล',
                'price' => 95,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            17 =>
            array (
                'id' => 18,
                'name_en' => 'Sapodila',
                'name_th' => 'ละมุด',
                'price' => 85,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            18 =>
            array (
                'id' => 19,
                'name_en' => 'Pear china',
                'name_th' => 'สาลี่หอม',
                'price' => 600,
                'image' => NULL,
                'desc_en' => '1x7kg',
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            19 =>
            array (
                'id' => 20,
                'name_en' => 'Dragon Fruit',
                'name_th' => 'แก้วมังกร',
                'price' => 575,
                'image' => NULL,
                'desc_en' => '1x10kg',
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            20 =>
            array (
                'id' => 21,
                'name_en' => ' Jack Fruit Rip',
                'name_th' => 'ขนุนสุก',
                'price' => 35,
                'image' => NULL,
                'desc_en' => '1 Nos 7-10Kg',
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            21 =>
            array (
                'id' => 22,
                'name_en' => ' Young Jack Fruit',
                'name_th' => 'ขนุนอ่อนหัน',
                'price' => 52,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            22 =>
            array (
                'id' => 23,
                'name_en' => 'Kiwi Fruit',
                'name_th' => 'ลูกกีวี',
                'price' => 26,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 3,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            23 =>
            array (
                'id' => 24,
                'name_en' => 'Avocado',
                'name_th' => 'อโวคาโด',
                'price' => 99,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 4,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            24 =>
            array (
                'id' => 25,
                'name_en' => 'Yang Mango ',
                'name_th' => 'มะม่วงเบา',
                'price' => 40,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            25 =>
            array (
                'id' => 26,
                'name_en' => 'Green Sweet Mango ',
            'name_th' => 'มะม่วงมัน(ฟ้าลัน)',
                'price' => 45,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            26 =>
            array (
                'id' => 27,
                'name_en' => 'Mangoes,Ripe',
                'name_th' => 'มะม่วงสุก',
                'price' => 68,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            27 =>
            array (
                'id' => 28,
                'name_en' => 'Papaya',
                'name_th' => 'มะละกอสุก',
                'price' => 29,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            28 =>
            array (
                'id' => 29,
                'name_en' => 'Papaya For Cooking',
                'name_th' => 'มะละกอเขียว',
                'price' => 24,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            29 =>
            array (
                'id' => 30,
                'name_en' => 'Young Coconut',
                'name_th' => 'มะพร้าวอ่อน',
                'price' => 22,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            30 =>
            array (
                'id' => 31,
                'name_en' => 'Pomeloes ',
                'name_th' => 'ส้มโอ',
                'price' => 49,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            31 =>
            array (
                'id' => 32,
                'name_en' => 'Pineapple ',
                'name_th' => 'สัปปะรด ',
                'price' => 27,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            32 =>
            array (
                'id' => 33,
                'name_en' => 'Cantalupe',
                'name_th' => 'แคนตาลูป',
                'price' => 45,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            33 =>
            array (
                'id' => 34,
                'name_en' => 'Guava ',
                'name_th' => 'ฝรั่งกิมจู',
                'price' => 42,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            34 =>
            array (
                'id' => 35,
                'name_en' => 'Longan',
                'name_th' => 'ลำไย',
                'price' => 90,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 3,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            35 =>
            array (
                'id' => 36,
                'name_en' => 'Rambutan',
                'name_th' => 'เงาะ',
                'price' => 35,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 4,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            36 =>
            array (
                'id' => 37,
                'name_en' => 'Red Ross Apple',
                'name_th' => 'ชมพู่แดง',
                'price' => 90,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            37 =>
            array (
                'id' => 38,
                'name_en' => 'Zalacca',
                'name_th' => 'สละ',
                'price' => 95,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            38 =>
            array (
                'id' => 39,
                'name_en' => 'Long gonk',
                'name_th' => 'ลองกอง',
                'price' => 95,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            39 =>
            array (
                'id' => 40,
                'name_en' => 'Mangosteen',
                'name_th' => 'มังคุด',
                'price' => 40,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            40 =>
            array (
                'id' => 41,
                'name_en' => 'Lychee',
                'name_th' => 'ลิ้นจี่',
                'price' => 40,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            41 =>
            array (
                'id' => 42,
                'name_en' => 'Sweet Tamarind',
                'name_th' => 'มะขามหวาน',
                'price' => 40,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            42 =>
            array (
                'id' => 43,
                'name_en' => 'Lime',
                'name_th' => 'ลูกมะนาว  ',
                'price' => 72,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            43 =>
            array (
                'id' => 44,
                'name_en' => 'Lemon',
                'name_th' => 'เลม่อน',
                'price' => 148,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            44 =>
            array (
                'id' => 45,
                'name_en' => 'Tapioka/Uaikayu',
                'name_th' => 'มันสำปะหลัง',
                'price' => 30,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            45 =>
            array (
                'id' => 46,
                'name_en' => 'Potatoes ,Sweet',
                'name_th' => 'มันเทศไข่',
                'price' => 34,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            46 =>
            array (
                'id' => 47,
                'name_en' => 'Potato ',
                'name_th' => 'มันฝรั่ง   ',
                'price' => 37,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 3,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            47 =>
            array (
                'id' => 48,
                'name_en' => 'Yam Bean',
                'name_th' => 'มันแกว',
                'price' => 38,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 4,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            48 =>
            array (
                'id' => 49,
                'name_en' => 'Turnip',
                'name_th' => 'หัวไชเท้า',
                'price' => 30,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            49 =>
            array (
                'id' => 50,
                'name_en' => 'Okra',
                'name_th' => 'กระเจี้ยบเขียว',
                'price' => 75,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            50 =>
            array (
                'id' => 51,
                'name_en' => 'Garlice pellless',
                'name_th' => 'กระเทียมจีนปลอก',
                'price' => 90,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            51 =>
            array (
                'id' => 52,
                'name_en' => 'Garlice ',
                'name_th' => 'กระเทียมจีนกลีบใหญ่',
                'price' => 79,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            52 =>
            array (
                'id' => 53,
                'name_en' => 'Yellow Ginger / Kunyit',
                'name_th' => 'ขมิ้นเหลือง',
                'price' => 67,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            53 =>
            array (
                'id' => 54,
                'name_en' => 'Galanga Roots / Lengkuas',
                'name_th' => 'ข่าอ่อน',
                'price' => 68,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            54 =>
            array (
                'id' => 55,
                'name_en' => 'Sliced Ginger',
                'name_th' => 'ขิงซอย',
                'price' => 80,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            55 =>
            array (
                'id' => 56,
                'name_en' => 'Ginger,Old',
                'name_th' => 'ขิงหัวแก่',
                'price' => 88,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            56 =>
            array (
                'id' => 57,
                'name_en' => 'Young Corn',
                'name_th' => 'ข้าวโพดอ่อน',
                'price' => 60,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            57 =>
            array (
                'id' => 58,
                'name_en' => 'Corn On Cob',
                'name_th' => 'ข้าวโพดฟัก',
                'price' => 38,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            58 =>
            array (
                'id' => 59,
                'name_en' => 'Kale/Kailan',
                'name_th' => 'คะน้าต้น',
                'price' => 38,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 3,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            59 =>
            array (
                'id' => 60,
                'name_en' => 'Baby Kailan',
                'name_th' => 'แขนงคะน้า',
                'price' => 50,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 4,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            60 =>
            array (
                'id' => 61,
            'name_en' => 'Celery (local)',
                'name_th' => 'คื่นไฉ่ไทย',
                'price' => 120,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            61 =>
            array (
                'id' => 62,
                'name_en' => 'Carrot ',
                'name_th' => 'แครอท',
                'price' => 41,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            62 =>
            array (
                'id' => 63,
                'name_en' => 'Acacia',
                'name_th' => 'ชะอม',
                'price' => 180,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            63 =>
            array (
                'id' => 64,
            'name_en' => 'Cauliflower (Trimmed)',
            'name_th' => 'ดอกกระหล่ำ (แต่ง)',
                'price' => 80,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            64 =>
            array (
                'id' => 65,
                'name_en' => 'Spring Onion',
                'name_th' => 'ต้นหอม ',
                'price' => 100,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            65 =>
            array (
                'id' => 66,
                'name_en' => 'Lemon glass',
                'name_th' => 'ตะใคร้  ',
                'price' => 36,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            66 =>
            array (
                'id' => 67,
                'name_en' => 'Cucumber large',
                'name_th' => 'แตงร้าน',
                'price' => 24,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            67 =>
            array (
                'id' => 68,
                'name_en' => 'Bean French',
                'name_th' => 'ถั่วแขก',
                'price' => 95,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            68 =>
            array (
                'id' => 69,
                'name_en' => 'Bean sprouts',
                'name_th' => 'ถั่วงอก',
                'price' => 25,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            69 =>
            array (
                'id' => 70,
                'name_en' => 'Bean Long/String beans',
                'name_th' => 'ถั่วฝักยาว',
                'price' => 43,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            70 =>
            array (
                'id' => 71,
                'name_en' => 'Snow beans',
                'name_th' => 'ถั่วลันเตา',
                'price' => 168,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 3,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            71 =>
            array (
                'id' => 72,
                'name_en' => 'Wing Bean',
                'name_th' => 'ถั่วพู',
                'price' => 90,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 4,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            72 =>
            array (
                'id' => 73,
                'name_en' => 'Leek',
                'name_th' => 'ต้นกระเทียมไทย',
                'price' => 190,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            73 =>
            array (
                'id' => 74,
                'name_en' => 'Broccoli',
                'name_th' => 'บล็อกโคลี่  ',
                'price' => 88,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            74 =>
            array (
                'id' => 75,
                'name_en' => 'Green gourd',
                'name_th' => 'บวบเหลี่ยม',
                'price' => 35,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            75 =>
            array (
                'id' => 76,
                'name_en' => 'Basil leaf',
                'name_th' => 'ใบกระเพรา   ',
                'price' => 93,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            76 =>
            array (
                'id' => 77,
            'name_en' => 'Boiled wild leaves (Kee-Lek)',
                'name_th' => 'ใบขี้เหล็ก/ดอกขื้หล็กต้ม',
                'price' => 68,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            77 =>
            array (
                'id' => 78,
                'name_en' => 'Kaffir leaves',
                'name_th' => 'ใบมะกูด ',
                'price' => 105,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            78 =>
            array (
                'id' => 79,
                'name_en' => 'Kaffir Whole',
                'name_th' => 'ลูกมะกรูด   ',
                'price' => 90,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            79 =>
            array (
                'id' => 80,
                'name_en' => 'Pandan Leaf',
                'name_th' => 'ใบเตย',
                'price' => 40,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            80 =>
            array (
                'id' => 81,
                'name_en' => 'Banan Leaf',
                'name_th' => 'ใบตอง',
                'price' => 35,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            81 =>
            array (
                'id' => 82,
                'name_en' => 'Mint leaves',
                'name_th' => 'ใบสะระแหน่    ',
                'price' => 158,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            82 =>
            array (
                'id' => 83,
                'name_en' => 'Sweet Basil Leaf',
                'name_th' => 'ใบโหรพา  ',
                'price' => 95,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 3,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            83 =>
            array (
                'id' => 84,
                'name_en' => 'Cha Muang Leaf',
                'name_th' => 'ใบชะมวง',
                'price' => 45,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 4,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            84 =>
            array (
                'id' => 85,
                'name_en' => 'Yee Ra Leaf',
                'name_th' => 'ใบยี่หร่า',
                'price' => 90,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            85 =>
            array (
                'id' => 86,
                'name_en' => 'Green Lettuce',
                'name_th' => 'ผักกาดหอม',
                'price' => 70,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            86 =>
            array (
                'id' => 87,
                'name_en' => 'Mustard Green / Chye Sim',
                'name_th' => 'ผักกวางตุ้งต้น',
                'price' => 28,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            87 =>
            array (
                'id' => 88,
                'name_en' => 'Lettuce Iceberg Green',
                'name_th' => 'ผักกาดแก้ว',
                'price' => 115,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            88 =>
            array (
                'id' => 89,
            'name_en' => 'Cabbage Long/Chinese (Lui)',
                'name_th' => 'ผักกาดขาวลุ้ย',
                'price' => 42,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            89 =>
            array (
                'id' => 90,
                'name_en' => 'Pickle Lettuce',
                'name_th' => 'ผักกาดดอง  ',
                'price' => 45,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            90 =>
            array (
                'id' => 91,
            'name_en' => 'Spinach (local)',
                'name_th' => 'ผักขม  ไทย',
                'price' => 53,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            91 =>
            array (
                'id' => 92,
                'name_en' => 'Parsley Chinese',
                'name_th' => 'ผักชีไทย มีราก',
                'price' => 145,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            92 =>
            array (
                'id' => 93,
                'name_en' => 'Grass Water',
                'name_th' => 'ผักบุ้งจีน',
                'price' => 40,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            93 =>
            array (
                'id' => 94,
            'name_en' => 'Bokchoy (Sophon)',
                'name_th' => 'ผักไต้หวัน',
                'price' => 45,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            94 =>
            array (
                'id' => 95,
                'name_en' => 'Cabbages White / Dremhead',
                'name_th' => 'กล่ำปลีขาว    ',
                'price' => 25,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 3,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            95 =>
            array (
                'id' => 96,
                'name_en' => 'Green Chilli Padi',
                'name_th' => 'พริกขี้หนูขียวเด็ดก้าน',
                'price' => 115,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 4,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            96 =>
            array (
                'id' => 97,
                'name_en' => 'Red Chilli Padi',
                'name_th' => 'พริกขี้หนูแดงเด็ดก้าน',
                'price' => 120,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            97 =>
            array (
                'id' => 98,
                'name_en' => 'Pepper Chilies Green',
                'name_th' => 'พริกชี้ฟ้าเขียว',
                'price' => 85,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            98 =>
            array (
                'id' => 99,
                'name_en' => 'Pepper Chilies Red',
                'name_th' => 'พริกชี้ฟ้าแดง',
                'price' => 90,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            99 =>
            array (
                'id' => 100,
                'name_en' => 'Young pepper corn',
                'name_th' => 'พริกไทยอ่อน',
                'price' => 210,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            100 =>
            array (
                'id' => 101,
                'name_en' => 'Capsicum,Green',
                'name_th' => 'พริกยักษ์หวาน เขียว ',
                'price' => 155,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            101 =>
            array (
                'id' => 102,
                'name_en' => 'Capsicum,Red',
                'name_th' => 'พริกยักษ์หวาน แดง',
                'price' => 155,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            102 =>
            array (
                'id' => 103,
                'name_en' => 'Capsicum,Yellow',
                'name_th' => 'พริกยักษ์หวาน เหลือง',
                'price' => 155,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            103 =>
            array (
                'id' => 104,
                'name_en' => 'Marrow',
                'name_th' => 'ฟักเขียว',
                'price' => 21,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            104 =>
            array (
                'id' => 105,
            'name_en' => 'Pumpkin (whole)',
                'name_th' => 'ฟักทองแก่',
                'price' => 25,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            105 =>
            array (
                'id' => 106,
            'name_en' => 'Taro (whole)',
                'name_th' => 'เผือกดิบ',
                'price' => 86,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            106 =>
            array (
                'id' => 107,
                'name_en' => 'Tomato',
                'name_th' => 'มะเขือเทศ',
                'price' => 33,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 3,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            107 =>
            array (
                'id' => 108,
                'name_en' => 'Cherry tomatoes',
                'name_th' => 'มะเขือเทศเชอร์รี่',
                'price' => 100,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 4,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            108 =>
            array (
                'id' => 109,
                'name_en' => 'Green egg plant',
                'name_th' => 'มะเขือเปราะ',
                'price' => 38,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            109 =>
            array (
                'id' => 110,
            'name_en' => 'Cherry egg plant (trimmed)',
                'name_th' => 'มะเขือพวงเด็ด',
                'price' => 115,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            110 =>
            array (
                'id' => 111,
                'name_en' => 'Purple egg plant',
                'name_th' => 'มะเขือม่วงยาว',
                'price' => 45,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            111 =>
            array (
                'id' => 112,
                'name_en' => 'Long Egg plant/Brinjal',
                'name_th' => 'มะเขือยาว',
                'price' => 41,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            112 =>
            array (
                'id' => 113,
                'name_en' => 'Bitter  Gourd/Cavilla',
                'name_th' => 'มะระจีน',
                'price' => 41,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            113 =>
            array (
                'id' => 114,
                'name_en' => 'Chayote',
                'name_th' => 'มะระหวาน',
                'price' => 75,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            114 =>
            array (
                'id' => 115,
                'name_en' => 'Coconut heart',
                'name_th' => 'ยอดมะพร้าวอ่อน',
                'price' => 90,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            115 =>
            array (
                'id' => 116,
            'name_en' => 'Local southern fruit (Sa-Taw)nut',
                'name_th' => 'สะตอแกะเม็ด',
                'price' => 600,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            116 =>
            array (
                'id' => 117,
            'name_en' => 'Local southern fruit (Sa-Taw)w/shell',
                'name_th' => 'สะตอฝัก',
                'price' => 250,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            117 =>
            array (
                'id' => 118,
                'name_en' => 'Look Nieng',
                'name_th' => 'ลูกเนียง',
                'price' => 75,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            118 =>
            array (
                'id' => 119,
            'name_en' => 'Preserved bamboo shoot (whole)',
                'name_th' => 'หน่อไม้ ก้อน',
                'price' => 90,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 3,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            119 =>
            array (
                'id' => 120,
                'name_en' => 'Preserved bamboo shoot',
                'name_th' => 'หน่อไม้ ดอง',
                'price' => 63,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 4,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            120 =>
            array (
                'id' => 121,
                'name_en' => 'Fresh bamboo shoot',
                'name_th' => 'หน่อไม้ ไผ่ตงหั่นสด',
                'price' => 78,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            121 =>
            array (
                'id' => 122,
                'name_en' => 'Asparagus',
                'name_th' => 'หน่อไม้ ฝรั่ง',
                'price' => 178,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            122 =>
            array (
                'id' => 123,
            'name_en' => 'Shallots (whole big) /Bawan Bombay',
                'name_th' => 'หอมแขก',
                'price' => 42,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            123 =>
            array (
                'id' => 124,
            'name_en' => 'Shallots (whole Small) /Bawan merah',
                'name_th' => 'หอมแดง',
                'price' => 89,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            124 =>
            array (
                'id' => 125,
                'name_en' => 'Onion Large',
                'name_th' => 'หอมหัวใหญ่',
                'price' => 25,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            125 =>
            array (
                'id' => 126,
                'name_en' => 'Whole mushroom',
                'name_th' => 'เห็ดฟาง',
                'price' => 168,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            126 =>
            array (
                'id' => 127,
                'name_en' => 'Black Jelly Mushroom',
                'name_th' => 'เห็ดหูหนู',
                'price' => 105,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            127 =>
            array (
                'id' => 128,
                'name_en' => 'King Oyster Mushroom',
                'name_th' => 'เห็ดนางรมหลวง',
                'price' => 98,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            128 =>
            array (
                'id' => 129,
                'name_en' => 'Angle mushroom',
                'name_th' => 'เห็ดนางฟ้า',
                'price' => 140,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            129 =>
            array (
                'id' => 130,
                'name_en' => 'Shitakae mushroom',
                'name_th' => 'เห็ดหอมสด',
                'price' => 250,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            130 =>
            array (
                'id' => 131,
                'name_en' => 'Enokin mushroom',
                'name_th' => 'เห็ดเข็มทอง',
                'price' => 128,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 3,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            131 =>
            array (
                'id' => 132,
                'name_en' => 'Banana spourts',
                'name_th' => 'หัวปลีกล้วย',
                'price' => 35,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 4,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            132 =>
            array (
                'id' => 133,
                'name_en' => 'Bunga kantan',
                'name_th' => 'ดอกดาหรา',
                'price' => 110,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            133 =>
            array (
                'id' => 134,
                'name_en' => 'Daun kesom/kesom leaf',
                'name_th' => 'ผักไผ่',
                'price' => 110,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            134 =>
            array (
                'id' => 135,
                'name_en' => 'Daun kari/kari leaf',
                'name_th' => 'ยอดหมุย',
                'price' => 115,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            135 =>
            array (
                'id' => 136,
                'name_en' => 'Leaf soup',
                'name_th' => 'ผักหวาน',
                'price' => 155,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            136 =>
            array (
                'id' => 137,
                'name_en' => 'Fresh Old coconut',
                'name_th' => 'มะพร้าวแก่',
                'price' => 39,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            137 =>
            array (
                'id' => 138,
                'name_en' => 'Fresh coconut whole',
                'name_th' => 'มะพร้าวทึนทึก',
                'price' => 38,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            138 =>
            array (
                'id' => 139,
                'name_en' => 'Yellow ginger leaf',
                'name_th' => 'ใบขมิ้น',
                'price' => 58,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            139 =>
            array (
                'id' => 140,
                'name_en' => 'Cashew leaves',
                'name_th' => 'ยอดมะม่วงหิมพานต์',
                'price' => 118,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            140 =>
            array (
                'id' => 141,
                'name_en' => 'Olive leaf',
                'name_th' => 'ยอดมะกอก',
                'price' => 116,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            141 =>
            array (
                'id' => 142,
                'name_en' => 'Leaf Asiatic',
                'name_th' => 'ใบบัวบก',
                'price' => 98,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            142 =>
            array (
                'id' => 143,
                'name_en' => 'Ulam Pucuk Raja',
                'name_th' => 'ผักชีล้อม',
                'price' => 80,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 3,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            143 =>
            array (
                'id' => 144,
                'name_en' => 'Tamarine/Asam Jawa',
                'name_th' => 'มะขามสด',
                'price' => 80,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 4,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            144 =>
            array (
                'id' => 145,
                'name_en' => 'Coriender Leaf',
                'name_th' => 'ผักชีฝรั่ง',
                'price' => 105,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            145 =>
            array (
                'id' => 146,
                'name_en' => 'Vegetable Drill',
                'name_th' => 'ผักชีลาว',
                'price' => 126,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            146 =>
            array (
                'id' => 147,
                'name_en' => 'Vegetable Chives',
                'name_th' => 'ใบก้ยช่าย',
                'price' => 86,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            147 =>
            array (
                'id' => 148,
            'name_en' => 'Tapioka Leaf (yong leaf)',
                'name_th' => 'ใบกระเจี้ยบอ่อน',
                'price' => 60,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            148 =>
            array (
                'id' => 149,
                'name_en' => 'Daun Kadok',
                'name_th' => 'ใบชะพลู',
                'price' => 60,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            149 =>
            array (
                'id' => 150,
                'name_en' => 'Parsley - English',
            'name_th' => 'ผักชีเพสลี่ (แต่งหน้าอาหาร)',
                'price' => 189,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            150 =>
            array (
                'id' => 151,
                'name_en' => 'Zuchini',
                'name_th' => 'แตงกวา ญี่ปุ่น',
                'price' => 118,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            151 =>
            array (
                'id' => 152,
                'name_en' => 'Wet Tamarine',
                'name_th' => 'มะขามเปียก',
                'price' => 130,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            152 =>
            array (
                'id' => 153,
                'name_en' => 'Tube Bean Curd',
                'name_th' => 'เต้าหู้หลอด',
                'price' => 12,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            153 =>
            array (
                'id' => 154,
                'name_en' => 'Hard Bean Curd',
                'name_th' => 'เต้าหู้แข็ง',
                'price' => 15,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            154 =>
            array (
                'id' => 155,
                'name_en' => 'Young Bean Curd',
                'name_th' => 'เต้าหู้อ่อน',
                'price' => 14,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 3,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            155 =>
            array (
                'id' => 156,
                'name_en' => 'Fresh Yellow Noodle',
                'name_th' => 'หมี่เหลืองสด',
                'price' => 30,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 4,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            156 =>
            array (
                'id' => 157,
                'name_en' => 'Fresh L. Noodle',
                'name_th' => 'เส้นก๋วยเตี๋ยว',
                'price' => 27,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            157 =>
            array (
                'id' => 158,
                'name_en' => 'Rice Chinese Noodle',
                'name_th' => 'ขนมจีน',
                'price' => 28,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            158 =>
            array (
                'id' => 159,
                'name_en' => 'Fresh Chan Noodle',
                'name_th' => 'เส้นจันทร์ผัดไทย',
                'price' => 40,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            159 =>
            array (
                'id' => 160,
                'name_en' => 'Thai Curry Spice red curry paste',
                'name_th' => 'พริกแกงเผ็ด',
                'price' => 90,
                'image' => NULL,
                'desc_en' => '1KG',
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            160 =>
            array (
                'id' => 161,
                'name_en' => 'Massaman cerry past',
                'name_th' => 'พริกแกงมัสมั่น',
                'price' => 108,
                'image' => NULL,
                'desc_en' => '1KG',
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            161 =>
            array (
                'id' => 162,
                'name_en' => 'Chili fresh-sour yellow curry',
                'name_th' => 'แกงสมพริกสด',
                'price' => 100,
                'image' => NULL,
                'desc_en' => '1KG',
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            162 =>
            array (
                'id' => 163,
                'name_en' => 'Sour yellow curry paste',
                'name_th' => 'พริกแกงพะแนง',
                'price' => 94,
                'image' => NULL,
                'desc_en' => '1KG',
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            163 =>
            array (
                'id' => 164,
                'name_en' => 'Yellow curry paste',
                'name_th' => 'พริกแกงเหลือง',
                'price' => 90,
                'image' => NULL,
                'desc_en' => '1KG',
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            164 =>
            array (
                'id' => 165,
                'name_en' => 'Green curry paste',
                'name_th' => 'แกงเขียวหวาน',
                'price' => 90,
                'image' => NULL,
                'desc_en' => '1KG',
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            165 =>
            array (
                'id' => 166,
                'name_en' => 'Cendol',
                'name_th' => 'ลอดช่อง',
                'price' => 29,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 2,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            166 =>
            array (
                'id' => 167,
                'name_en' => 'Black Jelly',
                'name_th' => 'เฉาก๊วย',
                'price' => 30,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 3,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            167 =>
            array (
                'id' => 168,
                'name_en' => 'Yoghurt',
                'name_th' => 'โยเกิต',
                'price' => 12,
                'image' => NULL,
                'desc_en' => '1x90g',
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 4,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            168 =>
            array (
                'id' => 169,
                'name_en' => 'Sweet shrimp',
                'name_th' => 'กุ้งหวาน',
                'price' => 225,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            169 =>
            array (
                'id' => 170,
                'name_en' => 'Chicken Chinese Sausage',
                'name_th' => 'เชียงไก่',
                'price' => 255,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            170 =>
            array (
                'id' => 171,
                'name_en' => 'Fresh Egg No1',
                'name_th' => 'ไข่ไก่ เบอร์1',
                'price' => 1500,
                'image' => NULL,
                'desc_en' => '360pcs',
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            171 =>
            array (
                'id' => 172,
                'name_en' => 'Duck salted eggs',
                'name_th' => 'ไข่เค็ม',
                'price' => 250,
                'image' => NULL,
                'desc_en' => '1x30pcs',
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            172 =>
            array (
                'id' => 173,
                'name_en' => 'Quail egg peeler',
                'name_th' => 'ไข่นกกระทาปอก',
                'price' => 2,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
            173 =>
            array (
                'id' => 174,
                'name_en' => 'Preserved egg',
                'name_th' => 'ไข่เยี่ยวม้า',
                'price' => 12,
                'image' => NULL,
                'desc_en' => NULL,
                'desc_th' => NULL,
                'created_at' => '2020-09-07 19:18:17',
                'updated_at' => '2020-09-07 19:18:17',
                'supplier_id' => 21,
                'brand_id' => 1,
                'category_id' => 1,
                'unit_id' => 1,
            ),
        ));


    }
}
